language: go

go:
  - 1.13.3

install: true

script: chmod +x build.sh && ./build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "VJH3IVxQmz5y8hvEQqA+eElnEH+iDJMUHb122CV7+xHK5KXp1AITug+b/+zd1Sm5IDRnfkFmBMSUqFHmVJ+wv7RYAK9kUiLsXRIrOYEMVLJS82AOlU3dJLeXPT1+e81spYDfH9Th+r8qNbjTaYWdmhdIiWjoKsohr2o2Sohvul+IiMvNy2TWSuKSgVWbp5uP8PcefFcvu6pbeeTfUCnx+R7ZEqAymb/s2NUQS+gW3sxgyiUHCjm/S4jUC4CW2AjwKTTon0KhRufIsOsb6N+bxHaOkTSa84Kby2V/RDzb7kixVeF7mEKyKEO4Ysk5/69P6oei77qCsUr0zV/XgZOBk+sPQuKEayTp8F0bB8zcugEuufPWAK29xmv01cjDWz2V31BGAmY++6DXbW6QfmCpOZR89qR4Gc/doEZDdXKxCfRmulIl3fOTiqosOzaZNgBU827b8G8juzmewvOwM5E8PiBsNQOXVflx/Mevw+G+8D0uDFfVsRChi65894dYh70Ovo+dnI3lyHpRWQBP9hK7zoZJka5Gk6BJJlSbs9IL+JQCDJX1O+HAqx0hSbH2yHFLITTXlMEVtbQKYMWvZ/a8kxFl1Q0bFUs7b+qiGTgBBcKQdKxkuWpyU3Wf3FVAgJjUZmFXiHV7A+5kUp8rPcZsGxfiqGpk+AUST44gbaAJJQU="
  file:
    - bin/pkimanager-linux-386
    - bin/pkimanager-linux-amd64
    - bin/pkimanager-linux-arm
    - bin/pkimanager-linux-arm64
  on:
    tags: true
